[package]
name = "axdtb"
version = "0.1.0"
edition = "2021"

[dependencies]
dtb-walker = "0.1.3"
lazy_init = {path="../../crates/lazy_init"}
axhal = {path="../../modules/axhal"}
log = "0.4.22"
byteorder = {version="1.5.0" , default-features=false}
